default: &default
  version: 'Rush-4'
  moments_on_wall: 6

development:
  <<: *default
  admin:
    email: 'demo@demo.com'

test:
  <<: *default
  admin:
    email: 'demo@demo.com'

production:
  <<: *default
  admin:
    email: 'jasl123@126.com'