default: &default
  identity_map_enabled: true
  pool_size: 5

development:
  <<: *default
  host: localhost
  database: tick_tock_development

test:
  <<: *default
  host: localhost
  database: tick_tock_test

production:
  sessions:
    default:
      hosts:
        - localhost:27017
      database: tick_tock
      username:
      password:
  options:
    allow_dynamic_fields: false
    identity_map_enabled: true
    include_root_in_json: true
    include_type_for_serialization: true
    preload_models: true
    scope_overwrite_exception: true
    raise_not_found_error: false
    skip_version_check: false
    use_activesupport_time_zone: false
    use_utc: true
